services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit_booking
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - aquadrop-latam

volumes:
  booking_postgres_data:

networks:
  aquadrop-latam:
    driver: bridge
    name: aquadrop-latam
